/* ============================================================================
   POISON PLANT FINDER — plant database
   Educational use only. Not medical advice. In an emergency call your local
   emergency number; in the US, Poison Control is 1-800-222-1222.
   ----------------------------------------------------------------------------
   Severity scale
   1  Irritant     Mild, short-lived discomfort
   2  Harmful      Real illness if ingested / notable skin reaction
   3  Toxic        Serious poisoning; medical care needed
   4  Severe       Can require hospitalization; risk of lasting harm
   5  Deadly       Can kill; small amounts may be fatal
   ============================================================================ */

const SEVERITY = {
  1: { label: "Irritant", tag: "Mild irritant" },
  2: { label: "Harmful",  tag: "Harmful if eaten" },
  3: { label: "Toxic",    tag: "Seriously toxic" },
  4: { label: "Severe",   tag: "Severe — can hospitalize" },
  5: { label: "Deadly",   tag: "Deadly — can be fatal" },
};

/* Controlled vocabularies used by the trait filter */
const VOCAB = {
  veins: ["Pinnate (feather)", "Palmate (hand)", "Parallel", "Needle / scale"],
  arrangement: ["Alternate", "Opposite", "Whorled", "Basal rosette", "Compound leaflets"],
  sun: ["Full sun", "Part shade", "Shade"],
  water: ["Dry", "Average", "Moist", "Wet / aquatic"],
  flowerColor: ["White", "Yellow", "Pink / Purple", "Red / Orange", "Green / none"],
};

const PLANTS = [
  {
    id: "poison-ivy",
    common: "Poison Ivy",
    scientific: "Toxicodendron radicans",
    family: "Anacardiaceae",
    aka: ["Eastern poison ivy"],
    severity: 4,
    contactHazard: true,
    native: "Eastern & central North America",
    invasive: { status: "Native (aggressive)", regions: "Native across most of North America; spreads aggressively along trails, fences and woodland edges.", },
    removal: {
      shouldRemove: true,
      urgency: "Remove from yards, paths and play areas.",
      method: "Dig out the whole root, or cut at the base and treat regrowth. Bag and trash it — do not compost.",
      precautions: "Cover all skin: gloves, long sleeves, boots. NEVER burn it — the smoke carries urushiol into your lungs and eyes and can cause life-threatening reactions. Wash tools and clothes separately afterward.",
      disposal: "Seal in plastic bags and put in the trash. Never burn.",
    },
    traits: {
      leaf: "Three pointed leaflets on each stem; the middle leaflet has a longer stalk. Edges may be smooth, toothed or lobed. Often glossy; red in spring and fall.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Feather-like veins branching from a central midrib on each leaflet.",
      flower: "Tiny greenish-white flowers in summer, then clusters of waxy pale berries.",
      flowerColor: ["Green / none", "White"],
      sun: ["Full sun", "Part shade", "Shade"], water: ["Dry", "Average", "Moist"],
      climate: "USDA zones 4–10. Woodland edges, fences, riverbanks, disturbed ground.",
      lookalikes: "Boxelder seedlings and Virginia creeper (which has FIVE leaflets — harmless). Remember: 'leaves of three, let it be.'",
    },
    danger: {
      ingest: "Rarely eaten, but ingestion can cause severe internal irritation — seek emergency care.",
      skin: "The oil urushiol causes an itchy, blistering rash 12–72 hours after contact. The oil clings to clothes, tools, and pet fur and stays active for years.",
      eyes: "Oil transferred to the eyes causes painful swelling — flush with water and see a doctor.",
      animals: "Pets usually aren't affected by the rash but carry the oil on their fur and pass it to you.",
      anaphylaxis: "Severe reactions can cause widespread swelling; smoke from burning plants can trigger dangerous airway reactions needing emergency care.",
    },
    firstAid: "Wash skin with soap and cool water within 30 minutes; rubbing alcohol helps strip the oil. Don't scratch. Cool compresses, calamine and oral antihistamines ease itching. See a doctor for facial/eye involvement, large areas, or trouble breathing.",
    emergency: "Call emergency services for trouble breathing, swelling of the face or throat, or after inhaling smoke from burning plants.",
  },
  {
    id: "poison-oak",
    common: "Poison Oak",
    scientific: "Toxicodendron diversilobum / T. pubescens",
    family: "Anacardiaceae",
    aka: ["Western poison oak", "Atlantic poison oak"],
    severity: 4,
    contactHazard: true,
    native: "Western North America (Pacific coast) and the US Southeast",
    invasive: { status: "Native (aggressive)", regions: "Native; forms dense thickets in chaparral, oak woodland and along trails." },
    removal: {
      shouldRemove: true,
      urgency: "Remove near homes, trails and grazing areas.",
      method: "Dig out roots when soil is moist, or cut and treat stumps. Bag and trash.",
      precautions: "Full skin cover and gloves. NEVER burn — the smoke is dangerous to inhale. Wash everything that touched it; the oil lingers on tools and clothing.",
      disposal: "Double-bag and trash. Never burn or compost.",
    },
    traits: {
      leaf: "Three leaflets shaped like oak leaves, with rounded lobes. Glossy green, turning red/orange in fall.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Lobed, oak-like leaflets with feather venation.",
      flower: "Small greenish-yellow flower clusters, then whitish berries.",
      flowerColor: ["Green / none", "White"],
      sun: ["Full sun", "Part shade"], water: ["Dry", "Average"],
      climate: "USDA zones 5–10. Chaparral, oak woodland, scrub; grows as a shrub or climbing vine.",
      lookalikes: "True oak seedlings (harmless) and blackberry. Three leaflets is the warning sign.",
    },
    danger: {
      ingest: "Causes severe internal irritation if eaten — seek emergency care.",
      skin: "Urushiol oil triggers a blistering, itchy rash 1–3 days after contact. Oil persists on fur, tools and clothing.",
      eyes: "Severe swelling and pain if oil reaches the eyes — flush and see a doctor.",
      animals: "Pets carry the oil on their coats and transfer it to people.",
      anaphylaxis: "Smoke inhalation and severe reactions can affect the airway — treat as an emergency.",
    },
    firstAid: "Same as poison ivy: wash with soap and cool water within 30 minutes, don't scratch, use calamine and antihistamines. See a doctor for facial/eye involvement or breathing problems.",
    emergency: "Emergency care for airway swelling, trouble breathing, or smoke inhalation.",
  },
  {
    id: "poison-sumac",
    common: "Poison Sumac",
    scientific: "Toxicodendron vernix",
    family: "Anacardiaceae",
    aka: ["Swamp sumac"],
    severity: 4,
    contactHazard: true,
    native: "Wetlands of the eastern United States and Canada",
    invasive: { status: "Native", regions: "Native to bogs, swamps and wet woodlands in eastern North America." },
    removal: {
      shouldRemove: true,
      urgency: "Remove only where people may contact it; it lives in wetlands.",
      method: "Cut and treat stumps; wear full protection. Often best handled by a professional in boggy ground.",
      precautions: "Cover all skin; gloves and eye protection. NEVER burn — sumac smoke is especially hazardous. Considered the most potent of the urushiol plants.",
      disposal: "Bag and trash. Never burn.",
    },
    traits: {
      leaf: "7–13 smooth-edged leaflets arranged in pairs along a reddish stem, with one leaflet at the tip. Bright orange-red in fall.",
      veins: "Pinnate (feather)", arrangement: "Compound leaflets", veinNote: "Pinnately compound — paired leaflets with a single tip leaflet; smooth (not toothed) margins.",
      flower: "Loose clusters of small greenish flowers, then drooping ivory-white berries (harmless sumacs have upright RED berry cones).",
      flowerColor: ["Green / none", "White"],
      sun: ["Part shade", "Full sun"], water: ["Wet / aquatic", "Moist"],
      climate: "USDA zones 3–9. Swamps, bogs and wet, shady ground.",
      lookalikes: "Harmless staghorn/smooth sumac have UPRIGHT red fuzzy berry clusters and toothed leaflets. White, drooping berries = poison sumac.",
    },
    danger: {
      ingest: "Severe internal irritation — seek emergency care.",
      skin: "Most potent urushiol plant; causes intense blistering rash. Oil persists on everything it touches.",
      eyes: "Severe swelling — flush and see a doctor.",
      animals: "Pets transfer the oil on their fur.",
      anaphylaxis: "Burning produces highly toxic smoke; severe airway reactions are possible.",
    },
    firstAid: "Wash with soap and cool water within 30 minutes. Calamine, cool compresses and antihistamines for the rash. See a doctor for large areas, the face, or breathing trouble.",
    emergency: "Emergency care for airway involvement or smoke inhalation.",
  },
  {
    id: "stinging-nettle",
    common: "Stinging Nettle",
    scientific: "Urtica dioica",
    family: "Urticaceae",
    aka: ["Common nettle"],
    severity: 1,
    contactHazard: true,
    native: "Europe, Asia and North America",
    invasive: { status: "Native (weedy)", regions: "Native across the Northern Hemisphere; spreads on rich, disturbed soil, field edges and damp ground." },
    removal: {
      shouldRemove: false,
      urgency: "Remove from paths and play areas; otherwise it's valuable for wildlife.",
      method: "Dig out the yellow spreading roots when soil is moist; mow repeatedly to weaken a patch.",
      precautions: "Wear thick gloves and long sleeves — the stinging hairs go through thin fabric. The sting is harmless to most people but unpleasant.",
      disposal: "Compost or trash; roots regrow easily, so don't scatter root pieces.",
    },
    traits: {
      leaf: "Heart-shaped, deeply toothed leaves in opposite pairs, covered in fine stinging hairs.",
      veins: "Pinnate (feather)", arrangement: "Opposite", veinNote: "Toothed leaves with net venation; square-ish stems bristling with stinging hairs.",
      flower: "Drooping strings of tiny greenish flowers where the leaves meet the stem, in summer.",
      flowerColor: ["Green / none"],
      sun: ["Part shade", "Full sun"], water: ["Moist", "Average"],
      climate: "USDA zones 3–10. Hedgerows, ditches, woodland edges and rich disturbed ground.",
      lookalikes: "Resembles dead-nettles and mint, which don't sting. The fine hairs and the sting on contact confirm it.",
    },
    danger: {
      ingest: "Cooking destroys the sting, and young leaves are a traditional cooked green and tea — but raw leaves sting the mouth. Forage only if you're certain of the ID.",
      skin: "Stinging hairs inject irritants (histamine and others) on contact, causing instant stinging, redness and bumps that usually fade within hours.",
      eyes: "Hairs in the eye cause stinging and irritation — flush with water; see a doctor if it persists.",
      animals: "Generally avoided by animals; can sting the nose and mouth of curious pets.",
      anaphylaxis: "True allergy is rare, but sensitive people can get widespread hives (urticaria — named after this plant). Severe whole-body reactions are uncommon but possible.",
    },
    firstAid: "Don't rub it (that pushes hairs in). Rinse with water, then lift hairs off with tape; cool the area and use antihistamine or hydrocortisone cream for itching. The sting normally fades within a few hours.",
    emergency: "Rarely needed — but seek care for eye stings that don't settle, or any sign of a whole-body allergic reaction (widespread hives, swelling, trouble breathing).",
  },
  {
    id: "giant-hogweed",
    common: "Giant Hogweed",
    scientific: "Heracleum mantegazzianum",
    family: "Apiaceae",
    aka: ["Cartwheel-flower", "Giant cow parsnip"],
    severity: 5,
    contactHazard: true,
    native: "Caucasus region of Western Asia",
    invasive: { status: "Invasive (often regulated)", regions: "Federally listed noxious weed in the US and invasive across the UK, Canada and Europe. Often must be reported to authorities." },
    removal: {
      shouldRemove: true,
      urgency: "Yes — remove and, in many areas, REPORT it to local authorities before touching it.",
      method: "Professional removal is strongly advised. If permitted, cut and dig the taproot wearing full protection on an overcast day, away from sunlight.",
      precautions: "DANGEROUS sap. Full waterproof cover: face shield, goggles, gloves, sealed sleeves. Sap on skin + sunlight causes severe burns. Keep all skin covered and out of the sun. Wash thoroughly and stay out of sunlight for 48 hours after any exposure.",
      disposal: "Bag securely; follow local noxious-weed disposal rules. Do not compost or burn.",
    },
    traits: {
      leaf: "Enormous deeply cut, jagged leaves up to 1.5 m (5 ft) wide; coarse and lobed.",
      veins: "Palmate (hand)", arrangement: "Alternate", veinNote: "Large palmately divided leaves with spreading veins; thick stems with purple blotches and stiff bristles.",
      flower: "Huge flat-topped umbrella of tiny white flowers up to 0.8 m (2.5 ft) across; plant can reach 5 m (15+ ft).",
      flowerColor: ["White"],
      sun: ["Full sun", "Part shade"], water: ["Moist", "Wet / aquatic"],
      climate: "USDA zones 3–8. Riverbanks, ditches, roadsides and damp waste ground.",
      lookalikes: "Native cow parsnip and Queen Anne's lace are much smaller. Giant size, purple-blotched bristly stems and huge flower heads are the giveaways.",
    },
    danger: {
      ingest: "Toxic if eaten — seek emergency care.",
      skin: "Sap contains furanocoumarins. On skin exposed to sunlight it causes phytophotodermatitis: severe burns and large blisters within 24–48 hours, with scars and light-sensitivity lasting years.",
      eyes: "Sap in the eyes can cause temporary or PERMANENT blindness. Flush immediately and get emergency care.",
      animals: "Sap can burn animals' skin and mouths.",
      anaphylaxis: "Not typically allergic, but burns can be severe and widespread enough to need hospital burn care.",
    },
    firstAid: "Get out of sunlight immediately. Wash sap off with soap and water, keep the area covered from sunlight for 48 hours. For eye contact, flush with water and seek emergency care. See a doctor for any blistering.",
    emergency: "Emergency care for eye exposure, large burns, or facial involvement. Protect burned skin from sun for months.",
  },
  {
    id: "wild-parsnip",
    common: "Wild Parsnip",
    scientific: "Pastinaca sativa",
    family: "Apiaceae",
    aka: ["Poison parsnip"],
    severity: 3,
    contactHazard: true,
    native: "Europe and Asia",
    invasive: { status: "Invasive", regions: "Invasive across much of North America; lines roadsides, fields and trails." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from yards, trails and pastures.",
      method: "Dig or cut below the crown before it seeds. Mow only when fully covered, and not in bright sun.",
      precautions: "Sap + sunlight burns skin. Cover all skin, wear gloves and eye protection, and work on overcast days or evenings. Wash exposed skin and keep it out of the sun.",
      disposal: "Bag and trash. Don't burn.",
    },
    traits: {
      leaf: "Toothed, mitten-shaped leaflets in pairs along the stem; yellow-green.",
      veins: "Pinnate (feather)", arrangement: "Compound leaflets", veinNote: "Pinnately compound leaves; grooved stem.",
      flower: "Flat-topped umbrella clusters of small YELLOW flowers — unusual among look-alikes that are white.",
      flowerColor: ["Yellow"],
      sun: ["Full sun"], water: ["Dry", "Average"],
      climate: "USDA zones 2–9. Roadsides, fields, prairies and disturbed ground.",
      lookalikes: "Resembles a tall dill or parsnip. The bright yellow flower umbrella sets it apart from white-flowered relatives.",
    },
    danger: {
      ingest: "The cultivated root is edible, but handling the foliage is the real hazard; toxic if wild parts are eaten in quantity.",
      skin: "Sap causes phytophotodermatitis — painful burns and blisters where sap-covered skin meets sunlight.",
      eyes: "Sap can irritate or damage the eyes — flush and seek care.",
      animals: "Can cause skin and mouth irritation in grazing animals.",
      anaphylaxis: "Burns rather than allergy; severe cases need medical care.",
    },
    firstAid: "Wash sap off promptly, keep skin out of sunlight for 48 hours, treat blisters as burns and see a doctor for anything beyond minor.",
    emergency: "Seek care for eye exposure or extensive blistering.",
  },
  {
    id: "poison-hemlock",
    common: "Poison Hemlock",
    scientific: "Conium maculatum",
    family: "Apiaceae",
    aka: ["Spotted hemlock", "Devil's porridge"],
    severity: 5,
    contactHazard: false,
    native: "Europe, North Africa and West Asia",
    invasive: { status: "Invasive (toxic weed)", regions: "Invasive across North America; common on roadsides, fields and stream banks." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from areas near people, children, pets and livestock.",
      method: "Dig out the taproot when soil is moist, before flowering. Wear gloves and a mask; avoid crushing it (fumes).",
      precautions: "All parts are poisonous. Wear gloves and don't touch your face. NEVER burn — smoke is toxic to inhale. Wash hands and tools after.",
      disposal: "Bag and trash. Never burn; do not feed to animals or compost.",
    },
    traits: {
      leaf: "Fern-like, finely divided lacy leaves; smell unpleasant (musty/mousy) when crushed.",
      veins: "Pinnate (feather)", arrangement: "Compound leaflets", veinNote: "Finely dissected, fern-like leaves on smooth, hollow stems.",
      flower: "Umbrella clusters of tiny white flowers. KEY SIGN: smooth, hollow green stems with distinct PURPLE/red blotches.",
      flowerColor: ["White"],
      sun: ["Full sun", "Part shade"], water: ["Average", "Moist"],
      climate: "USDA zones 4–8. Roadsides, ditches, fields and stream banks.",
      lookalikes: "Easily confused with Queen Anne's lace, wild carrot and edible parsley/parsnip. The purple-spotted, hairless stem and musty smell are warning signs — when unsure, do not touch or taste.",
    },
    danger: {
      ingest: "Contains coniine and related alkaloids. Eating any part can be fatal: it causes paralysis that spreads to the muscles you breathe with. This is the plant said to have killed Socrates.",
      skin: "Toxins can be absorbed through skin and broken skin; handle only with gloves.",
      eyes: "Irritant; avoid contact and flush if exposed.",
      animals: "Highly poisonous to livestock, horses and pets; deaths are common in grazing animals.",
      anaphylaxis: "Acts as a nerve poison rather than an allergen, but is rapidly life-threatening if eaten.",
    },
    firstAid: "If any part is eaten, call Poison Control / emergency services immediately — do not wait for symptoms. There is no home remedy.",
    emergency: "Eating any amount is a medical emergency. Call emergency services / Poison Control right away.",
  },
  {
    id: "water-hemlock",
    common: "Water Hemlock",
    scientific: "Cicuta maculata",
    family: "Apiaceae",
    aka: ["Spotted cowbane", "Beaver poison"],
    severity: 5,
    contactHazard: false,
    native: "North America",
    invasive: { status: "Native (extremely toxic)", regions: "Native to wet meadows, marshes and stream edges across North America." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from pastures and areas near people and animals.",
      method: "Dig out the entire chambered root; professional help is wise near water. Keep livestock away.",
      precautions: "Often called the most poisonous plant in North America. Wear gloves; never let the root contact mouth or broken skin. Do not burn.",
      disposal: "Bag securely and trash. Never compost, burn or feed to animals.",
    },
    traits: {
      leaf: "Twice/thrice-divided leaves with toothed leaflets; veins end in the NOTCHES between teeth (not the tips) — a key clue.",
      veins: "Pinnate (feather)", arrangement: "Compound leaflets", veinNote: "Leaf veins run to the notches of the teeth, not the points. Stout, hollow, often purple-streaked stems.",
      flower: "Umbrella clusters of small white flowers, like a larger Queen Anne's lace.",
      flowerColor: ["White"],
      sun: ["Full sun", "Part shade"], water: ["Wet / aquatic", "Moist"],
      climate: "USDA zones 3–8. Marshes, wet meadows, ditches and stream banks.",
      lookalikes: "Confused with edible water parsnip and Queen Anne's lace. The chambered, fleshy root base is highly toxic. Never forage in this family without expert ID.",
    },
    danger: {
      ingest: "Contains cicutoxin. A single bite of the root can cause violent seizures and death within hours. Among the most lethal plants in North America.",
      skin: "Toxin can be absorbed through cuts; handle with gloves only.",
      eyes: "Irritant; avoid and flush if exposed.",
      animals: "Rapidly fatal to cattle, horses and other livestock that graze the roots.",
      anaphylaxis: "A fast-acting convulsant poison, not an allergen — but immediately life-threatening.",
    },
    firstAid: "If any part is eaten, this is a dire emergency — call emergency services immediately. Seizures can begin within an hour.",
    emergency: "Eating any amount is a life-threatening emergency. Call emergency services / Poison Control at once.",
  },
  {
    id: "oleander",
    common: "Oleander",
    scientific: "Nerium oleander",
    family: "Apocynaceae",
    aka: ["Rose laurel"],
    severity: 5,
    contactHazard: false,
    native: "Mediterranean region and Southwest Asia",
    invasive: { status: "Ornamental (escapes in warm areas)", regions: "Planted worldwide as an ornamental hedge; naturalizes in warm regions like the US Southwest and Gulf Coast." },
    removal: {
      shouldRemove: false,
      urgency: "Not required, but keep it away from children, pets and grazing animals; consider removing where they roam.",
      method: "If removing, cut and dig the roots wearing gloves. Keep clippings away from animals.",
      precautions: "All parts are toxic, including dried leaves and smoke. NEVER burn clippings. Don't use stems as skewers or in cooking fires.",
      disposal: "Bag and trash. Never burn; keep away from animals and water sources.",
    },
    traits: {
      leaf: "Long, narrow, leathery dark-green leaves in whorls of three; leaves stay evergreen.",
      veins: "Pinnate (feather)", arrangement: "Whorled", veinNote: "Narrow lance-shaped leaves with a prominent pale midrib; clear sap.",
      flower: "Showy clusters of five-petaled flowers in white, pink or red, often fragrant, all summer.",
      flowerColor: ["White", "Pink / Purple", "Red / Orange"],
      sun: ["Full sun"], water: ["Dry", "Average"],
      climate: "USDA zones 8–11. Hedges, highway medians and gardens in warm climates.",
      lookalikes: "Distinctive showy shrub; the danger is that it's common and beautiful, so people underestimate it.",
    },
    danger: {
      ingest: "Contains cardiac glycosides (oleandrin). Eating even a few leaves, or honey/water/skewers contaminated by it, can cause fatal heart-rhythm disturbances.",
      skin: "Sap can irritate skin; wash after handling.",
      eyes: "Sap irritates the eyes — flush thoroughly.",
      animals: "Extremely toxic to dogs, cats, horses, cattle and birds; a few leaves can kill.",
      anaphylaxis: "A heart poison rather than an allergen, but rapidly dangerous if ingested.",
    },
    firstAid: "If any part is eaten by a person or pet, call Poison Control / emergency services or a vet immediately. Don't wait for symptoms.",
    emergency: "Ingestion is a medical emergency — heart-rhythm effects can be fatal. Call for help right away.",
  },
  {
    id: "foxglove",
    common: "Foxglove",
    scientific: "Digitalis purpurea",
    family: "Plantaginaceae",
    aka: ["Lady's glove", "Dead man's bells"],
    severity: 4,
    contactHazard: false,
    native: "Western Europe",
    invasive: { status: "Ornamental (naturalizes)", regions: "Widely grown in gardens; naturalized in parts of North America, especially the Pacific Northwest." },
    removal: {
      shouldRemove: false,
      urgency: "Keep away from children and pets; remove where small children play.",
      method: "Pull or dig wearing gloves; deadhead before seeding if you want to limit spread.",
      precautions: "All parts are toxic. Wear gloves; wash hands well, since the toxin can be absorbed and is potent. Keep away from herbal teas — it has been mistaken for comfrey.",
      disposal: "Bag and trash; keep away from compost used on food gardens.",
    },
    traits: {
      leaf: "Soft, fuzzy, gray-green oval leaves with toothed edges in a rosette the first year.",
      veins: "Pinnate (feather)", arrangement: "Basal rosette", veinNote: "Deeply veined, wrinkled, downy leaves; net-like veins.",
      flower: "Tall spires of tubular thimble-shaped flowers, purple/pink/white, often spotted inside.",
      flowerColor: ["Pink / Purple", "White"],
      sun: ["Part shade", "Full sun"], water: ["Average", "Moist"],
      climate: "USDA zones 4–9. Woodland edges, clearings and cottage gardens.",
      lookalikes: "First-year rosettes resemble comfrey and mullein — never use unknown fuzzy-leaved plants for tea.",
    },
    danger: {
      ingest: "Contains digitalis cardiac glycosides. Eating leaves, flowers or seeds can cause nausea, vision changes and dangerous heart-rhythm changes that can be fatal. (Digitalis is also a real heart medication — which is exactly why it's so potent.)",
      skin: "Generally low risk, but wash after handling; sensitive people may react.",
      eyes: "Irritant; flush if exposed.",
      animals: "Toxic to dogs, cats, horses and livestock.",
      anaphylaxis: "A heart poison rather than an allergen, but dangerous if eaten.",
    },
    firstAid: "If eaten, call Poison Control / emergency services immediately. Watch for nausea, slow or irregular pulse and confusion.",
    emergency: "Ingestion is a medical emergency due to heart effects. Call for help right away.",
  },
  {
    id: "belladonna",
    common: "Deadly Nightshade",
    scientific: "Atropa belladonna",
    family: "Solanaceae",
    aka: ["Belladonna"],
    severity: 5,
    contactHazard: false,
    native: "Europe, North Africa and Western Asia",
    invasive: { status: "Naturalized (toxic)", regions: "Naturalized in parts of North America; found in shady, disturbed and limestone soils." },
    removal: {
      shouldRemove: true,
      urgency: "Remove where children might reach the tempting berries.",
      method: "Dig out the root wearing gloves; remove all berries first so they aren't eaten.",
      precautions: "All parts, especially the sweet berries, are deadly. Wear gloves; toxins can absorb through skin and eyes. Keep children far away.",
      disposal: "Bag and trash securely. Never compost where berries could be found.",
    },
    traits: {
      leaf: "Oval pointed leaves, dull green, often in unequal pairs (one large, one small).",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Soft oval leaves with net venation; bushy 1–2 m plant.",
      flower: "Bell-shaped, dull purple-brown flowers, then shiny black cherry-sized berries.",
      flowerColor: ["Pink / Purple", "Green / none"],
      sun: ["Part shade", "Shade"], water: ["Average", "Moist"],
      climate: "USDA zones 5–9. Shady woods, hedgerows and disturbed limestone soils.",
      lookalikes: "Berries look like edible cherries or currants — a deadly trap for children. Never eat unknown shiny black berries.",
    },
    danger: {
      ingest: "Contains tropane alkaloids (atropine, scopolamine). As few as 2–5 berries can kill a child; symptoms include dilated pupils, racing heart, hallucinations, fever and seizures.",
      skin: "Toxins absorb through skin; handle with gloves.",
      eyes: "Sap in the eyes dilates the pupil and blurs vision (this is the historical 'belladonna' cosmetic use) — flush and seek care.",
      animals: "Toxic to pets and livestock, though some animals tolerate it better than humans.",
      anaphylaxis: "A potent nerve poison rather than an allergen, but rapidly life-threatening.",
    },
    firstAid: "If any part is eaten, call Poison Control / emergency services immediately. Dilated pupils, dry mouth, flushing and confusion are warning signs.",
    emergency: "Ingestion — especially of berries by a child — is a life-threatening emergency. Call for help at once.",
  },
  {
    id: "castor-bean",
    common: "Castor Bean",
    scientific: "Ricinus communis",
    family: "Euphorbiaceae",
    aka: ["Castor oil plant", "Palma Christi"],
    severity: 5,
    contactHazard: false,
    native: "East Africa and the Mediterranean",
    invasive: { status: "Ornamental / invasive in warm areas", regions: "Grown as a bold ornamental; invasive in warm regions like the US Southwest, Gulf states and California." },
    removal: {
      shouldRemove: true,
      urgency: "Remove where children or pets could reach the colorful seeds.",
      method: "Pull or dig wearing gloves; remove and bag all seed pods first.",
      precautions: "The seeds contain ricin, one of the most poisonous natural substances. Wear gloves; never let anyone chew the seeds. Keep seeds away from children entirely.",
      disposal: "Bag seeds and plant separately and trash. Don't compost.",
    },
    traits: {
      leaf: "Huge star-shaped leaves with 5–11 pointed lobes, often deep red or bronze; bold and tropical-looking.",
      veins: "Palmate (hand)", arrangement: "Alternate", veinNote: "Large palmate (hand-shaped) leaves with radiating veins; reddish hollow stems.",
      flower: "Spiky red/green flower clusters, then soft spiny seed pods holding glossy mottled 'beans'.",
      flowerColor: ["Red / Orange", "Green / none"],
      sun: ["Full sun"], water: ["Average", "Moist"],
      climate: "USDA zones 9–11 (annual elsewhere). Gardens, roadsides and waste ground in warm areas.",
      lookalikes: "The mottled seeds look like attractive beans or ticks — never let them be handled as toys or eaten.",
    },
    danger: {
      ingest: "Seeds contain ricin. A few thoroughly chewed seeds can be fatal, causing severe vomiting, internal bleeding and organ failure. (Castor OIL is processed to remove ricin and is safe — the raw seed is not.)",
      skin: "Crushed seeds can irritate skin and cause allergic reactions in workers handling them.",
      eyes: "Irritant; flush if exposed.",
      animals: "Highly toxic to dogs, horses and livestock that eat the seeds.",
      anaphylaxis: "Dust from the seeds is a known allergen and can trigger asthma and severe allergic reactions in sensitive people.",
    },
    firstAid: "If seeds are chewed or swallowed, call Poison Control / emergency services immediately — even before symptoms appear.",
    emergency: "Chewing/swallowing seeds is a life-threatening emergency. Call for help right away.",
  },
  {
    id: "manchineel",
    common: "Manchineel",
    scientific: "Hippomane mancinella",
    family: "Euphorbiaceae",
    aka: ["Beach apple", "Tree of death ('arbol de la muerte')"],
    severity: 5,
    contactHazard: true,
    native: "Tropical Americas: Florida, Caribbean, Central America, northern South America",
    invasive: { status: "Native (protected, hazardous)", regions: "Native coastal tree; protected in places for dune stabilization, but extremely dangerous to people. Often marked with warning signs or red bands." },
    removal: {
      shouldRemove: false,
      urgency: "Usually protected — do NOT remove yourself. Avoid it and respect warning markings.",
      method: "Removal is for trained professionals only; the wood, sap and smoke are all hazardous.",
      precautions: "Don't touch the tree, stand under it in rain, or burn it. Sap drips burn skin; smoke can blind. Often marked with a painted red ring.",
      disposal: "Professional handling only.",
    },
    traits: {
      leaf: "Glossy, leathery oval leaves with finely toothed edges and a tiny gland where the leaf meets the stalk; yellow-green.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Shiny simple leaves with a small gland at the leaf base; milky caustic sap.",
      flower: "Small greenish flower spikes, then small green-yellow fruits that look like little apples.",
      flowerColor: ["Green / none"],
      sun: ["Full sun"], water: ["Average", "Moist"],
      climate: "USDA zones 10–11. Tropical and subtropical beaches and coastal mangroves.",
      lookalikes: "The fruit smells sweet and looks like a small apple — eating it can be fatal. Never eat unknown beach fruit.",
    },
    danger: {
      ingest: "The 'beach apple' fruit causes severe, potentially fatal swelling and burns of the mouth, throat and gut. Considered one of the most dangerous fruits in the world.",
      skin: "Milky sap causes severe burns and blisters. Standing under the tree in rain lets sap-laden water blister your skin.",
      eyes: "Sap or smoke in the eyes can cause intense pain and temporary BLINDNESS.",
      animals: "Toxic; though some native animals tolerate the fruit.",
      anaphylaxis: "Caustic chemical burns rather than allergy, but can be severe and widespread.",
    },
    firstAid: "Wash sap off immediately with water. For eye exposure, flush and seek emergency care. For any ingestion, call emergency services at once.",
    emergency: "Ingestion, eye exposure or large skin burns are emergencies. Get medical care immediately.",
  },
  {
    id: "daphne",
    common: "Daphne",
    scientific: "Daphne mezereum",
    family: "Thymelaeaceae",
    aka: ["Spurge laurel", "February daphne"],
    severity: 4,
    contactHazard: true,
    native: "Europe and Western Asia",
    invasive: { status: "Ornamental (naturalizes)", regions: "Popular fragrant garden shrub; naturalized in parts of North America." },
    removal: {
      shouldRemove: false,
      urgency: "Keep away from children who might eat the bright berries.",
      method: "Dig out wearing gloves; remove berries first.",
      precautions: "All parts, especially the berries, are toxic; sap irritates skin. Wear gloves and wash after pruning.",
      disposal: "Bag and trash; keep berries away from children.",
    },
    traits: {
      leaf: "Smooth, narrow, oval leaves clustered toward branch tips; semi-evergreen.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Simple leaves with a clear midrib; flowers appear before leaves on bare stems.",
      flower: "Highly fragrant pink-purple (or white) flowers in late winter, hugging the stems, then bright red (or yellow) berries.",
      flowerColor: ["Pink / Purple", "White"],
      sun: ["Part shade"], water: ["Average", "Moist"],
      climate: "USDA zones 4–7. Woodland gardens and shaded borders.",
      lookalikes: "Bright berries are tempting to children; all are toxic.",
    },
    danger: {
      ingest: "Berries and bark contain irritant toxins; a few berries can cause severe mouth/throat burning, vomiting and, in quantity, dangerous illness.",
      skin: "Sap causes blistering and rashes; wear gloves when handling.",
      eyes: "Sap irritates the eyes — flush thoroughly.",
      animals: "Toxic to dogs, cats and livestock.",
      anaphylaxis: "Irritant rather than allergen, but reactions can be severe.",
    },
    firstAid: "If berries are eaten, call Poison Control. Wash sap off skin; flush eyes if exposed.",
    emergency: "Seek care for ingestion, especially in children, or for severe skin/eye reactions.",
  },
  {
    id: "lily-of-the-valley",
    common: "Lily of the Valley",
    scientific: "Convallaria majalis",
    family: "Asparagaceae",
    aka: ["May bells", "Our Lady's tears"],
    severity: 4,
    contactHazard: false,
    native: "Europe and temperate Asia",
    invasive: { status: "Ornamental (spreads aggressively)", regions: "Common groundcover; spreads by runners and naturalizes in shady gardens and woods." },
    removal: {
      shouldRemove: false,
      urgency: "Keep away from children and pets; remove where toddlers play.",
      method: "Dig out the dense rhizome mats wearing gloves.",
      precautions: "All parts are toxic, including the water in a cut-flower vase. Wear gloves; keep berries and vase water away from children and pets.",
      disposal: "Bag and trash; pour vase water out of reach of pets.",
    },
    traits: {
      leaf: "Two or three broad, smooth, lance-shaped leaves rising from the base, with parallel veins.",
      veins: "Parallel", arrangement: "Basal rosette", veinNote: "Smooth strap-like leaves with parallel veins — a clue it's a lily relative, not an edible green.",
      flower: "Arching stems of small, fragrant, white nodding bells in spring; then small orange-red berries.",
      flowerColor: ["White"],
      sun: ["Shade", "Part shade"], water: ["Moist", "Average"],
      climate: "USDA zones 2–7. Shady gardens and woodlands.",
      lookalikes: "Young leaves resemble wild garlic/ramsons — a dangerous foraging mix-up. Wild garlic smells strongly of garlic; lily of the valley does not.",
    },
    danger: {
      ingest: "Contains cardiac glycosides. Eating leaves, flowers, berries or even drinking the vase water can cause nausea, slow or irregular heartbeat and, rarely, dangerous heart effects.",
      skin: "Low risk; wash after handling.",
      eyes: "Irritant; flush if exposed.",
      animals: "Toxic to dogs and cats; can cause serious heart effects in pets.",
      anaphylaxis: "A heart-active poison rather than an allergen.",
    },
    firstAid: "If eaten, call Poison Control / a vet for pets. Watch for stomach upset and heart-rhythm changes.",
    emergency: "Seek care for significant ingestion or any heart-rhythm symptoms.",
  },
  {
    id: "jimsonweed",
    common: "Jimsonweed",
    scientific: "Datura stramonium",
    family: "Solanaceae",
    aka: ["Thorn apple", "Devil's snare", "Datura"],
    severity: 5,
    contactHazard: false,
    native: "Likely Central America; now worldwide",
    invasive: { status: "Invasive weed", regions: "A weed of fields, barnyards and waste ground across North America and much of the world." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from yards, pastures and anywhere children or animals roam.",
      method: "Pull or dig wearing gloves before seed pods form; bag the spiny pods.",
      precautions: "All parts, especially seeds, are dangerous. Wear gloves; never let anyone brew it as a tea or 'natural high' — overdoses are common and deadly.",
      disposal: "Bag and trash. Never compost or feed to animals.",
    },
    traits: {
      leaf: "Large jagged-toothed leaves with an unpleasant smell when crushed.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Coarsely toothed leaves on stout, often purplish stems.",
      flower: "Large white or pale-purple trumpet flowers, then egg-shaped SPINY seed pods full of black seeds.",
      flowerColor: ["White", "Pink / Purple"],
      sun: ["Full sun"], water: ["Average", "Dry"],
      climate: "USDA zones 3–10 (annual). Disturbed ground, fields, barnyards and gardens.",
      lookalikes: "The spiny 'thorn apple' pod is distinctive. People are sometimes poisoned trying to use it recreationally — never do this.",
    },
    danger: {
      ingest: "Contains tropane alkaloids (atropine, scopolamine, hyoscyamine). Causes hallucinations, racing heart, high fever, seizures and death; doses are unpredictable.",
      skin: "Toxins can absorb through skin; handle with gloves.",
      eyes: "Sap dilates the pupil and blurs vision — flush and seek care.",
      animals: "Toxic to livestock and pets, though the smell deters most grazing.",
      anaphylaxis: "A nerve poison rather than an allergen, but rapidly dangerous.",
    },
    firstAid: "If any part is eaten, call Poison Control / emergency services immediately. Agitation, dilated pupils, dry hot skin and confusion are warning signs.",
    emergency: "Ingestion is a medical emergency. Call for help right away — do not try to 'wait it out.'",
  },
  {
    id: "pokeweed",
    common: "Pokeweed",
    scientific: "Phytolacca americana",
    family: "Phytolaccaceae",
    aka: ["Pokeberry", "Inkberry", "Poke sallet"],
    severity: 3,
    contactHazard: false,
    native: "Eastern North America",
    invasive: { status: "Native (weedy)", regions: "Native; weedy and spreading via berries eaten by birds. Considered invasive in parts of Europe and Asia." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from yards where children might eat the purple berries.",
      method: "Dig out the large taproot when young; mature roots are big and persistent.",
      precautions: "All parts are toxic raw, and toxicity increases as the plant ages. Wear gloves; the root is the most poisonous part. Keep berries away from children.",
      disposal: "Bag and trash; remove berries so birds don't spread them.",
    },
    traits: {
      leaf: "Large, smooth, oval leaves with a strong smell when bruised.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Big simple leaves on smooth reddish-purple stems; can reach 3 m tall.",
      flower: "Spikes of small greenish-white flowers, then drooping clusters of dark purple berries on bright magenta stems.",
      flowerColor: ["White", "Green / none"],
      sun: ["Full sun", "Part shade"], water: ["Average", "Moist"],
      climate: "USDA zones 4–9. Fence rows, clearings, gardens and disturbed ground.",
      lookalikes: "The juicy purple berries tempt children. Although some traditions cook young leaves ('poke sallet') through several water changes, this is risky — the safe choice is not to eat it.",
    },
    danger: {
      ingest: "Roots, mature leaves, stems and berries contain saponins and oxalate that cause severe vomiting, cramping and diarrhea; large amounts can be dangerous, especially to children.",
      skin: "Toxins can absorb through cuts when handling roots; wear gloves.",
      eyes: "Juice irritates the eyes — flush thoroughly.",
      animals: "Toxic to pets and livestock; pigs and some animals are especially sensitive.",
      anaphylaxis: "Mainly a gut irritant; reactions vary with the amount eaten.",
    },
    firstAid: "If eaten, call Poison Control; expect stomach upset. Seek care for children, large amounts, or persistent vomiting and dehydration.",
    emergency: "Seek urgent care for severe or prolonged vomiting, or any ingestion by a young child.",
  },
  {
    id: "angels-trumpet",
    common: "Angel's Trumpet",
    scientific: "Brugmansia spp.",
    family: "Solanaceae",
    aka: ["Tree datura"],
    severity: 5,
    contactHazard: false,
    native: "South America (Andes)",
    invasive: { status: "Ornamental (toxic)", regions: "Grown worldwide as a dramatic ornamental; naturalizes in warm climates. Extinct in the wild but common in cultivation." },
    removal: {
      shouldRemove: false,
      urgency: "Keep away from children and anyone who might misuse it.",
      method: "Prune and dig wearing gloves.",
      precautions: "All parts are highly toxic. Wear gloves; never let anyone make tea or use it recreationally — poisonings are frequently fatal or cause lasting harm.",
      disposal: "Bag and trash; keep clippings from children and animals.",
    },
    traits: {
      leaf: "Large soft oval leaves, often slightly furry, on a shrub or small tree.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Big simple leaves; woody shrub/tree form (vs. its weedy relative Datura).",
      flower: "Huge, fragrant, DROOPING trumpet flowers (white, yellow, pink or orange) hanging down — the easiest ID feature.",
      flowerColor: ["White", "Yellow", "Pink / Purple", "Red / Orange"],
      sun: ["Full sun", "Part shade"], water: ["Moist", "Average"],
      climate: "USDA zones 9–11 (container plant elsewhere). Gardens and patios.",
      lookalikes: "Hanging trumpet flowers distinguish it from upright-flowered Datura/Jimsonweed — both are dangerous.",
    },
    danger: {
      ingest: "Contains tropane alkaloids; eating or brewing any part causes hallucinations, racing heart, fever, seizures and death. Doses are wildly unpredictable.",
      skin: "Toxins can absorb through skin; wear gloves and wash after handling.",
      eyes: "Sap dilates the pupil — flush and seek care if exposed.",
      animals: "Toxic to pets and livestock.",
      anaphylaxis: "A nerve poison rather than an allergen, but rapidly life-threatening.",
    },
    firstAid: "If any part is eaten, call Poison Control / emergency services immediately.",
    emergency: "Ingestion is a medical emergency. Call for help right away.",
  },
  {
    id: "monkshood",
    common: "Monkshood",
    scientific: "Aconitum napellus",
    family: "Ranunculaceae",
    aka: ["Wolfsbane", "Aconite", "Devil's helmet"],
    severity: 5,
    contactHazard: true,
    native: "Mountains of Europe and Asia",
    invasive: { status: "Ornamental (deadly)", regions: "Grown in cottage and shade gardens; naturalized in some cool regions." },
    removal: {
      shouldRemove: false,
      urgency: "Keep well away from children and anyone who handles food; consider removing from family gardens.",
      method: "Dig out the tuberous roots wearing waterproof gloves.",
      precautions: "One of the most toxic garden plants. The toxin can absorb through SKIN — always wear gloves, never handle with bare hands or broken skin, and never let roots be mistaken for an edible tuber.",
      disposal: "Bag and trash; never compost or let roots near food crops.",
    },
    traits: {
      leaf: "Deeply divided, dark green palm-shaped leaves with pointed lobes.",
      veins: "Palmate (hand)", arrangement: "Alternate", veinNote: "Hand-shaped, deeply cut leaves; tall upright plant.",
      flower: "Tall spikes of hooded helmet-shaped flowers, usually deep blue-purple (sometimes white or yellow).",
      flowerColor: ["Pink / Purple", "White"],
      sun: ["Part shade", "Full sun"], water: ["Moist", "Average"],
      climate: "USDA zones 3–7. Cool, moist borders and woodland gardens.",
      lookalikes: "Roots have been fatally mistaken for horseradish or wild herbs. The hooded flower is distinctive — never forage near it.",
    },
    danger: {
      ingest: "Contains aconitine. Eating any part causes burning/tingling, numbness, vomiting, paralysis and fatal heart-rhythm changes, sometimes within hours.",
      skin: "Toxin absorbs through the skin; even handling crushed plant or roots bare-handed can cause tingling and numbness. Always wear gloves.",
      eyes: "Irritant; flush and seek care if exposed.",
      animals: "Highly toxic to pets and livestock.",
      anaphylaxis: "A fast heart/nerve poison rather than an allergen, but rapidly life-threatening.",
    },
    firstAid: "If eaten, call emergency services immediately. For heavy skin exposure with tingling/numbness, wash thoroughly and seek medical advice.",
    emergency: "Ingestion is a life-threatening emergency. Call for help right away; heart effects can be rapid.",
  },
  {
    id: "rhododendron",
    common: "Rhododendron & Azalea",
    scientific: "Rhododendron spp.",
    family: "Ericaceae",
    aka: ["Azalea"],
    severity: 3,
    contactHazard: false,
    native: "Asia, Europe and North America (many species)",
    invasive: { status: "Ornamental (some invasive)", regions: "Hugely popular shrubs; Rhododendron ponticum is seriously invasive in the UK and Ireland." },
    removal: {
      shouldRemove: false,
      urgency: "Keep clippings away from livestock and pets; remove invasive species where required.",
      method: "Cut and dig roots; for invasive ponticum, follow local control guidance.",
      precautions: "All parts contain grayanotoxins. Don't let goats, sheep or pets eat leaves or clippings. Don't use the wood for cooking skewers/fires near food.",
      disposal: "Bag and trash; keep clippings from animals.",
    },
    traits: {
      leaf: "Leathery, oval, often evergreen leaves clustered at branch tips (rhododendron); azaleas are often smaller-leaved and deciduous.",
      veins: "Pinnate (feather)", arrangement: "Alternate", veinNote: "Simple leathery leaves with a clear midrib; whorl-like clusters at stem tips.",
      flower: "Showy clusters of bell- or funnel-shaped flowers in nearly every color, in spring.",
      flowerColor: ["Pink / Purple", "White", "Red / Orange", "Yellow"],
      sun: ["Part shade", "Shade"], water: ["Moist", "Average"],
      climate: "USDA zones 4–9. Acidic woodland soils, gardens and hillsides.",
      lookalikes: "Very recognizable flowering shrubs; the hidden risk is honey made from the nectar ('mad honey'), which can poison people.",
    },
    danger: {
      ingest: "Leaves, flowers, nectar and 'mad honey' contain grayanotoxins, causing drooling, vomiting, low blood pressure, slow heartbeat and, in severe cases, dangerous heart effects.",
      skin: "Low risk; wash after handling.",
      eyes: "Mild irritant; flush if exposed.",
      animals: "Very toxic to grazing animals (sheep, goats, horses) and to pets; even a few leaves can sicken them.",
      anaphylaxis: "A heart/nerve toxin rather than an allergen.",
    },
    firstAid: "If eaten, call Poison Control / a vet. Watch for drooling, vomiting and slow heartbeat. Most human cases recover with care.",
    emergency: "Seek care for significant ingestion, heart-rhythm symptoms, or any large amount eaten by a pet or child.",
  },
  {
    id: "yew",
    common: "Yew",
    scientific: "Taxus baccata / T. cuspidata",
    family: "Taxaceae",
    aka: ["English yew", "Japanese yew"],
    severity: 5,
    contactHazard: false,
    native: "Europe, North Africa, West Asia (English yew); East Asia (Japanese yew)",
    invasive: { status: "Ornamental (deadly)", regions: "Classic evergreen hedge and churchyard tree; widely planted worldwide." },
    removal: {
      shouldRemove: false,
      urgency: "Keep clippings away from livestock and horses — dried clippings are deadly to them; remove where animals graze.",
      method: "Cut and dig wearing gloves; bag all clippings immediately.",
      precautions: "Nearly all parts (needles, bark, seeds) are deadly; only the red flesh of the berry is non-toxic, but the seed inside is. NEVER throw clippings into a paddock — horses die from eating dropped yew.",
      disposal: "Bag and trash all clippings the same day. Never leave them where animals can reach them.",
    },
    traits: {
      leaf: "Flat, narrow, dark-green needles in two rows along the twig; soft, not prickly.",
      veins: "Needle / scale", arrangement: "Alternate", veinNote: "Flat needle leaves with a single midrib, arranged in two rows; evergreen.",
      flower: "Non-flowering conifer; females bear a single seed in a fleshy red cup ('aril').",
      flowerColor: ["Green / none", "Red / Orange"],
      sun: ["Full sun", "Part shade", "Shade"], water: ["Average", "Moist"],
      climate: "USDA zones 5–7 (English); 4–7 (Japanese). Hedges, gardens, churchyards and woodland.",
      lookalikes: "The bright red berry-cup tempts children — the red flesh is harmless but the SEED inside is deadly. Never let children eat the 'berries.'",
    },
    danger: {
      ingest: "Needles and seeds contain taxine alkaloids. Eating even a small handful can cause sudden fatal heart-rhythm collapse, sometimes with little warning.",
      skin: "Low risk; wash after handling.",
      eyes: "Mild irritant; flush if exposed.",
      animals: "Among the most dangerous plants for horses and livestock; a mouthful of clippings can kill quickly.",
      anaphylaxis: "A rapid heart poison rather than an allergen.",
    },
    firstAid: "If needles or seeds are eaten, call emergency services immediately — heart effects can be sudden. For pets/horses, call a vet at once.",
    emergency: "Ingestion is a life-threatening emergency due to sudden cardiac effects. Call for help right away.",
  },
  {
    id: "english-ivy",
    common: "English Ivy",
    scientific: "Hedera helix",
    family: "Araliaceae",
    aka: ["Common ivy"],
    severity: 2,
    contactHazard: true,
    native: "Europe and Western Asia",
    invasive: { status: "Invasive", regions: "Invasive in much of North America (especially the Pacific Northwest) and elsewhere; smothers trees and ground." },
    removal: {
      shouldRemove: true,
      urgency: "Remove where it's climbing trees or buildings; it's a damaging invasive.",
      method: "Pull vines from the ground; cut a band around tree trunks and let upper growth die. Dig out roots to prevent regrowth.",
      precautions: "Sap can cause skin rashes in sensitive people. Wear gloves and long sleeves; wash after. Don't burn large amounts.",
      disposal: "Bag and trash; ivy roots easily from cuttings, so don't compost.",
    },
    traits: {
      leaf: "Glossy evergreen leaves, usually with 3–5 pointed lobes (juvenile) or unlobed oval leaves (mature, flowering growth).",
      veins: "Palmate (hand)", arrangement: "Alternate", veinNote: "Lobed leaves with pale palmate veins; clinging aerial rootlets on the vine.",
      flower: "Only mature growth flowers: greenish-yellow flower clusters in fall, then black berries.",
      flowerColor: ["Green / none"],
      sun: ["Shade", "Part shade", "Full sun"], water: ["Average", "Moist"],
      climate: "USDA zones 4–9. Woods, walls, fences and as a groundcover.",
      lookalikes: "Very common; the main risk is mild — skin reaction from sap and toxic berries if eaten.",
    },
    danger: {
      ingest: "Leaves and berries contain saponins; eating them causes mouth burning, drooling, vomiting and stomach upset. Rarely serious unless a lot is eaten.",
      skin: "Sap (falcarinol) causes allergic contact dermatitis in sensitive people, especially gardeners with repeated exposure.",
      eyes: "Sap irritates the eyes — flush if exposed.",
      animals: "Toxic to dogs and cats if eaten, causing drooling and vomiting.",
      anaphylaxis: "Contact allergy can build up over time; severe reactions are uncommon.",
    },
    firstAid: "Wash sap off skin; antihistamines for itching. If berries are eaten, call Poison Control; expect stomach upset.",
    emergency: "Seek care for large amounts eaten, severe skin reactions, or ingestion by a small child.",
  },
  {
    id: "tansy-ragwort",
    common: "Tansy Ragwort",
    scientific: "Jacobaea vulgaris (Senecio jacobaea)",
    family: "Asteraceae",
    aka: ["Common ragwort", "Stinking willie"],
    severity: 3,
    contactHazard: false,
    native: "Europe and Western Asia",
    invasive: { status: "Invasive (noxious weed)", regions: "Invasive and listed as a noxious weed in North America, Australia and New Zealand; serious threat to grazing land." },
    removal: {
      shouldRemove: true,
      urgency: "Remove from pastures and hay fields — it's deadly to horses and cattle, even when dried in hay.",
      method: "Pull or dig the whole root before flowering, ideally when soil is moist. Bag flowering plants so seeds don't spread.",
      precautions: "Wear gloves — the toxins can be absorbed and the plant can irritate skin. NEVER leave pulled plants in a field; wilted ragwort is still deadly and more palatable to animals.",
      disposal: "Bag and trash or follow local noxious-weed rules; do not leave in pastures or put in hay.",
    },
    traits: {
      leaf: "Deeply cut, ruffled dark-green leaves with a ragged outline; unpleasant smell.",
      veins: "Pinnate (feather)", arrangement: "Basal rosette", veinNote: "Ragged, deeply lobed leaves in a first-year rosette, then a tall flowering stem.",
      flower: "Flat-topped clusters of bright yellow daisy-like flowers, each with ~13 petals, in summer.",
      flowerColor: ["Yellow"],
      sun: ["Full sun"], water: ["Average", "Dry"],
      climate: "USDA zones 3–9. Pastures, roadsides, dunes and waste ground.",
      lookalikes: "Looks like other yellow daisies; the ragged leaves and pasture setting are clues. The danger is mostly to livestock.",
    },
    danger: {
      ingest: "Contains pyrrolizidine alkaloids that cause cumulative, irreversible LIVER damage. Dangerous to people only with repeated exposure (e.g., contaminated herbal teas or honey).",
      skin: "Toxins can be absorbed through skin with heavy handling; wear gloves.",
      eyes: "Mild irritant; flush if exposed.",
      animals: "Deadly to horses and cattle; they often avoid it fresh but eat it dried in hay, causing fatal liver disease.",
      anaphylaxis: "Cumulative liver toxin rather than an allergen.",
    },
    firstAid: "For people, avoid repeated exposure and contaminated products. For animals known to have eaten it, consult a vet — liver damage can appear weeks later.",
    emergency: "Seek veterinary care for affected animals; for people, see a doctor if liver symptoms (jaundice, fatigue) follow known exposure.",
  },
  {
    id: "cow-parsnip",
    common: "Cow Parsnip",
    scientific: "Heracleum maximum",
    family: "Apiaceae",
    aka: ["American cow parsnip"],
    severity: 3,
    contactHazard: true,
    native: "North America",
    invasive: { status: "Native", regions: "Native across much of North America; common in meadows, ditches and moist ground." },
    removal: {
      shouldRemove: false,
      urgency: "Remove only where people will brush against it; it's a native plant.",
      method: "Cut or dig wearing protection, on overcast days.",
      precautions: "Sap + sunlight burns skin (milder than giant hogweed, but real). Cover skin, wear gloves and eye protection, and keep sap off skin in sunlight.",
      disposal: "Bag and trash; don't burn.",
    },
    traits: {
      leaf: "Large, broad, maple-like leaves divided into three coarse, toothed segments; softly hairy.",
      veins: "Palmate (hand)", arrangement: "Alternate", veinNote: "Big three-part leaves with spreading veins; ridged, hairy, hollow stems.",
      flower: "Broad flat-topped umbrella of small white flowers; plant 1–2.5 m tall (smaller than giant hogweed).",
      flowerColor: ["White"],
      sun: ["Full sun", "Part shade"], water: ["Moist", "Wet / aquatic"],
      climate: "USDA zones 3–7. Wet meadows, stream banks, ditches and clearings.",
      lookalikes: "Smaller cousin of giant hogweed; both have phototoxic sap. If a hogweed-type plant is over 3 m with purple-blotched bristly stems, treat it as giant hogweed.",
    },
    danger: {
      ingest: "Some indigenous traditions ate cooked young stems, but the plant is easily confused with deadly relatives — the safe choice is not to forage it.",
      skin: "Sap causes phytophotodermatitis — burns and blisters where sap-covered skin meets sunlight (generally milder than giant hogweed).",
      eyes: "Sap can irritate or burn the eyes — flush and seek care.",
      animals: "Can irritate the skin and mouths of animals.",
      anaphylaxis: "Chemical burns rather than allergy.",
    },
    firstAid: "Wash sap off promptly, keep skin out of sunlight for 48 hours, treat blisters as burns. Flush eyes if exposed.",
    emergency: "Seek care for eye exposure or significant blistering.",
  },
  {
    id: "hydrangea",
    common: "Hydrangea",
    scientific: "Hydrangea macrophylla",
    family: "Hydrangeaceae",
    aka: ["Bigleaf hydrangea"],
    severity: 2,
    contactHazard: false,
    native: "Japan and East Asia (this species)",
    invasive: { status: "Ornamental", regions: "Popular garden shrub worldwide; not generally invasive." },
    removal: {
      shouldRemove: false,
      urgency: "Generally safe to keep; just don't let pets or children eat large amounts of leaves/buds.",
      method: "Prune normally; no special precautions for the gardener.",
      precautions: "Leaves, buds and flowers contain small amounts of cyanogenic glycosides. Don't let pets chew large quantities; keep flowers out of food and drinks.",
      disposal: "Normal garden waste; keep clippings from grazing pets.",
    },
    traits: {
      leaf: "Large, oval, toothed, glossy green leaves in opposite pairs.",
      veins: "Pinnate (feather)", arrangement: "Opposite", veinNote: "Bold simple leaves in opposite pairs with strong net venation.",
      flower: "Big rounded or flat flower heads in blue, pink, purple or white (color shifts with soil pH).",
      flowerColor: ["Pink / Purple", "White"],
      sun: ["Part shade", "Full sun"], water: ["Moist", "Average"],
      climate: "USDA zones 5–9. Gardens, borders and foundation plantings.",
      lookalikes: "Very recognizable; the toxicity is mild and only matters if a lot is eaten.",
    },
    danger: {
      ingest: "Leaves, buds and flowers contain cyanogenic glycosides; eating a large amount can cause stomach upset, and in theory cyanide-type effects, but serious poisoning is rare.",
      skin: "Sap can cause mild dermatitis in sensitive people; wash after handling.",
      eyes: "Mild irritant; flush if exposed.",
      animals: "Eating a lot can cause vomiting, drooling and lethargy in dogs, cats and horses.",
      anaphylaxis: "Mild contact reactions are possible but uncommon.",
    },
    firstAid: "If a large amount is eaten, call Poison Control / a vet; expect mostly stomach upset. Wash sap off skin.",
    emergency: "Seek care if a child or pet eats a large amount, or for unusual symptoms.",
  },
];

/* Make available to all pages */
if (typeof window !== "undefined") {
  window.PLANTS = PLANTS;
  window.SEVERITY = SEVERITY;
  window.VOCAB = VOCAB;
}
